### ISSUE TITLE
Is there any example? I want to implement this package in my own application and can't figure out where to start?  ❓ 

### ISSUE THREAD

**Issue by heromanofe** [ascheja/xml-rpc-kt#1]
I am using XML-RPC ( implementation group: 'org.apache.xmlrpc', name: 'xmlrpc-client', version: '3.1.3' ) and want to try out other packages to find best one, one of the reasons for switch is: sending attachments using that library takes too much time. I am fairy new to Ktor.

**Comment by ascheja** [comment]
Hi,

assuming you're able to get your hands on a [ktor client](https://ktor.io/docs/getting-started-ktor-client.html#create-client) you should be able to just create an instance of a `MethodCall` with the parameters you need and then use the [`xmlRpc` extension function](https://github.com/ascheja/xml-rpc-kt/blob/main/ktor-client-xmlrpc/src/main/kotlin/Library.kt#L24) like you would do a `get` or `post` request with ktor, only that you pass the `MethodCall` as the second argument
```kotlin
val client: HttpClient = createHttpClient()
val call = MethodCall("some-method", IntegerValue(42), StringValue("some-string"))
val response = client.xmlRpc("https://some-server/rpc", call) as MethodResponseSuccess // or check for MethodResponseFault if you set the parameter `throwOnFault = false`
val firstParam = response.params.firstOrNull() as? StringValue ?: error("expected first parameter of response to be a StringValue")

**Comment by heromanofe** [comment]
> 

Okay, I will try it out slowly with first step being: trying to replace my authentication system, will see if it works, it starts with
```
      Global.Common = object : XmlRpcClient() {init {
            setConfig(object : XmlRpcClientConfigImpl() {init {
                serverURL = URL(java.lang.String.format("%s/xmlrpc/2/common", Global.url))
                isEnabledForExceptions = true
                connectionTimeout = 5000
                replyTimeout = 5000

            }
            })
        }
        }
```
I read through these files and will see if it works, also is there any reason why I should use StringValue... (so Value) instead of directly something like: listOf(...) ?

**Comment by heromanofe** [comment]
I am getting this error:
![image](https://user-images.githubusercontent.com/51365889/161596626-a4ef67fd-5090-491f-9899-48b2e77af86c.png)

```java.lang.NoSuchMethodError: No virtual method writeBytes([B)V in class Ljava/io/ByteArrayOutputStream; or its super classes (declaration of 'java.io.ByteArrayOutputStream' appears in /apex/com.android.art/javalib/core-oj.jar)```

**Comment by ascheja** [comment]
I guess `writeBytes` is not part of the android api for `java.io.ByteArrayOutputStream`

**Comment by ascheja** [comment]
I just published version 1.0.1 which is using a different method on `ByteArrayOutputStream` to the same result.

> I read through these files and will see if it works, also is there any reason why I should use StringValue... (so Value) instead of directly something like: listOf(...) ?

I've opted for compile-time safety, as far as I know if you pass a unhandled type to Apache's xmlrpc you will get an exception at Runtime while here you will get a error at compile-time, but you have to pay with wrapping all values in the respective library type.

**Comment by heromanofe** [comment]
It worked, thanks! tomorrow will check it with attachments and if works, I will be writing some helper functions for myself cuz current format is hard to figure out, I use more of either Hashmap or Arrayof(hashmap)
![image](https://user-images.githubusercontent.com/51365889/161652553-bf75c46d-124e-4e69-b0ee-37c40e213460.png)

**Comment by heromanofe** [comment]
> I just published version 1.0.1 which is using a different method on `ByteArrayOutputStream` to the same result.
> 
> > I read through these files and will see if it works, also is there any reason why I should use StringValue... (so Value) instead of directly something like: listOf(...) ?
> 
> I've opted for compile-time safety, as far as I know if you pass a unhandled type to Apache's xmlrpc you will get an exception at Runtime while here you will get a error at compile-time, but you have to pay with wrapping all values in the respective library type.

I am not gonna lie, this won't be a problem if you do 2 things: 1. check how it handles null from server *in xml-rpc it throws unless your server has specific flag: allow nulls
2. if you make some easy way to wrap it, for example, helper function that turns everything into desired format.

**Comment by heromanofe** [comment]
Update: I can't figure out how to have: 
ArrayValue(StructValue)
So in kotlin it would be
listOf(hasMapOf(VALUE to KEY))
I've got struct working, but I am getting this error:
![image](https://user-images.githubusercontent.com/51365889/161742729-52bf1912-e4d5-4add-8ff5-e28b30a668e9.png)

**Comment by heromanofe** [comment]
![image](https://user-images.githubusercontent.com/51365889/161743384-a58f701b-3d97-4f7d-8823-0477ba1f0993.png)
Here are fields on server and my result is either binary or base64, based of which object I am attaching, if image: base64 else binary

**Comment by ascheja** [comment]
I'm not familiar with the server you're speaking to, but maybe try using `Base64Value` instead of `StringValue` for binary data.
As for your issue with `ArrayValue`: My guess is you have a wrong import, there is no `ConstantValue` in this library.
